import Mock from 'mockjs';

/**
 * 生成接口使用的数据
 * @returns
 */
function createData() {
  const List = Mock.mock({
    'list|10': [
      {
        id: '@id',
        createTime: '',
        updateTime: '',
        roleName: '@cname',
        remark: 'null',
      },
    ],
  });
  return List;
}

const treeData = [
  {
    id: 1,
    createTime: '',
    updateTime: '',
    pid: 0,
    name: '全部数据',
    code: null,
    toCode: null,
    type: 1,
    status: null,
    level: 1,
    children: [
      {
        id: 7,
        createTime: '',
        updateTime: '',
        pid: 1,
        name: '权限管理',
        code: 'Acl',
        toCode: null,
        type: 1,
        status: null,
        level: 2,
        children: [
          {
            id: 8,
            createTime: '',
            updateTime: '',
            pid: 7,
            name: '用户管理',
            code: 'User',
            toCode: null,
            type: 1,
            status: null,
            level: 3,
            children: [
              {
                id: 11,
                createTime: '',
                updateTime: '',
                pid: 8,
                name: '添加用户',
                code: 'btn.User.add',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 12,
                createTime: '',
                updateTime: '',
                pid: 8,
                name: '删除用户',
                code: 'btn.User.remove',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 13,
                createTime: '',
                updateTime: '',
                pid: 8,
                name: '修改用户',
                code: 'btn.User.update',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 14,
                createTime: '',
                updateTime: '',
                pid: 8,
                name: '修改用户',
                code: 'btn.User.assgin',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
            ],
          },
          {
            id: 9,
            createTime: '',
            updateTime: '',
            pid: 7,
            name: '角色管理',
            code: 'Role',
            toCode: null,
            type: 1,
            status: null,
            level: 3,
            children: [
              {
                id: 15,
                createTime: '',
                updateTime: '',
                pid: 9,
                name: '分配权限',
                code: 'btn.Role.assgin',
                toCode: 'RoleAuth',
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: false,
              },
              {
                id: 16,
                createTime: '',
                updateTime: '',
                pid: 9,
                name: '添加角色',
                code: 'btn.Role.add',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: false,
              },
              {
                id: 17,
                createTime: '',
                updateTime: '',
                pid: 9,
                name: '修改角色',
                code: 'btn.Role.update',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 18,
                createTime: '',
                updateTime: '',
                pid: 9,
                name: '删除角色',
                code: 'btn.Role.remove',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
            ],
            select: true,
          },
          {
            id: 10,
            createTime: '',
            updateTime: '',
            pid: 7,
            name: '菜单管理',
            code: 'Permission',
            toCode: null,
            type: 1,
            status: null,
            level: 3,
            children: [
              {
                id: 19,
                createTime: '',
                updateTime: '',
                pid: 10,
                name: '添加',
                code: 'btn.Permission.add',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 20,
                createTime: '',
                updateTime: '',
                pid: 10,
                name: '修改',
                code: 'btn.Permission.update',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 21,
                createTime: '',
                updateTime: '',
                pid: 10,
                name: '删除',
                code: 'btn.Permission.remove',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
            ],
            select: true,
          },
        ],
        select: true,
      },
      {
        id: 22,
        createTime: '',
        updateTime: '',
        pid: 10,
        name: '商品管理',
        code: 'product',
        toCode: null,
        type: 1,
        status: null,
        level: 2,
        children: [
          {
            id: 23,
            createTime: '',
            updateTime: '',
            pid: 22,
            name: '分类管理',
            code: 'Category',
            toCode: null,
            type: 1,
            status: null,
            level: 3,
            children: [
              {
                id: 28,
                createTime: '',
                updateTime: '',
                pid: 23,
                name: '添加子分类',
                code: 'btn.Category.add',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 29,
                createTime: '',
                updateTime: '',
                pid: 23,
                name: '修改分类',
                code: 'btn.Category.update',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 30,
                createTime: '',
                updateTime: '',
                pid: 23,
                name: '删除分类',
                code: 'btn.Category.remove',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
            ],
            select: true,
          },
          {
            id: 24,
            createTime: '',
            updateTime: '',
            pid: 22,
            name: '平台属性管理',
            code: 'Attr',
            toCode: null,
            type: 1,
            status: null,
            level: 3,
            children: [
              {
                id: 31,
                createTime: '',
                updateTime: '',
                pid: 24,
                name: '添加',
                code: 'btn.Attr.add',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 32,
                createTime: '',
                updateTime: '',
                pid: 24,
                name: '更新',
                code: 'btn.Attr.update',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 33,
                createTime: '',
                updateTime: '',
                pid: 24,
                name: '删除',
                code: 'btn.Attr.remove',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
            ],
            select: true,
          },
          {
            id: 25,
            createTime: '',
            updateTime: '',
            pid: 22,
            name: '品牌管理',
            code: 'Trademark',
            toCode: null,
            type: 2,
            status: null,
            level: 3,
            children: [
              {
                id: 34,
                createTime: '',
                updateTime: '',
                pid: 25,
                name: '添加品牌',
                code: 'btn.Trademark.add',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 35,
                createTime: '',
                updateTime: '',
                pid: 25,
                name: '修改品牌',
                code: 'btn.Trademark.update',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 36,
                createTime: '',
                updateTime: '',
                pid: 25,
                name: '删除品牌',
                code: 'btn.Trademark.remove',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
            ],
            select: true,
          },
          {
            id: 26,
            createTime: '',
            updateTime: '',
            pid: 22,
            name: 'SPU管理',
            code: 'Spu',
            toCode: null,
            type: 1,
            status: null,
            level: 3,
            children: [
              {
                id: 37,
                createTime: '',
                updateTime: '',
                pid: 26,
                name: '添加Sp',
                code: 'btn.Spu.add',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 38,
                createTime: '',
                updateTime: '',
                pid: 26,
                name: '修改Sp',
                code: 'btn.Spu.update',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 39,
                createTime: '',
                updateTime: '',
                pid: 26,
                name: '删除Spu',
                code: 'btn.Spu.remove',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
            ],
            select: true,
          },
          {
            id: 27,
            createTime: '',
            updateTime: '',
            pid: 22,
            name: 'SKU管理',
            code: 'Sku',
            toCode: null,
            type: 1,
            status: null,
            level: 3,
            children: [
              {
                id: 40,
                createTime: '',
                updateTime: '',
                pid: 27,
                name: '添加Sku',
                code: 'btn.Sku.add',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 41,
                createTime: '',
                updateTime: '',
                pid: 27,
                name: '修改Sku',
                code: 'btn.Sku.update',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
              {
                id: 42,
                createTime: '',
                updateTime: '',
                pid: 27,
                name: '删除Sku',
                code: 'btn.Sku.remove',
                toCode: null,
                type: 2,
                status: null,
                level: 4,
                children: [],
                select: true,
              },
            ],
            select: true,
          },
        ],
        select: true,
      },
    ],
    select: true,
  },
];

export default [
  {
    // 添加属性
    url: '/api/acl/role/:page/:limit',
    method: 'get',
    response: request => {
      const { query } = request;
      return {
        code: 200,
        message: '成功',
        data: {
          record: createData().list,
          total: 400,
          size: 2,
          current: 1,
          orders: [],
          optimizeCountSql: true,
          hitCount: false,
          countId: null,
          maxLimit: null,
          searchCount: true,
          pages: 16,
        },
        ok: true,
      };
    },
  },
  {
    // 添加属性
    url: '/api/acl/role/save',
    method: 'post',
    response: () => {
      return {
        code: 200,
        messgae: '成功',
        ok: true,
      };
    },
  },
  {
    // 修改属性
    url: '/api/acl/role/update',
    method: 'post',
    response: () => {
      return {
        code: 200,
        messgae: '成功',
        ok: true,
      };
    },
  },
  {
    url: '/api/acl/permission/toAssigin/:roleId',
    method: 'get',
    response: () => {
      return {
        code: 200,
        messgae: '成功',
        data: treeData,
        ok: true,
      };
    },
  },
  {
    url: '/api/acl/permission/doAssigin/:roleId',
    method: 'post',
    response: () => {
      return {
        code: 200,
        messgae: '成功',
        ok: true,
      };
    },
  },
  {
    url: '/api/acl/role/remove:roleId',
    method: 'delete',
    response: () => {
      return {
        code: 200,
        messgae: '成功',
        ok: true,
      };
    },
  },
];
